[build]
# rustflags = ["-C", "target-cpu=native"]
rustflags = ["-C", "link-args=-Wl,-rpath,/opt/tops/lib"]
# rustflags = ["-C", "link-args=-Wl,-rpath,/xxx/caps/build/lib"] # for debug candle-gcu + topsruntime

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=-avx,-avx2"]